<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
	<TargetFramework>$(UDTTargetFramework)</TargetFramework>
	<RootNamespace>UniversalDeviceToolkit.SpectrumTester</RootNamespace>
	<OutputType>Exe</OutputType>
	<AssemblyName>SpectrumTester</AssemblyName>
	<SelfContained>false</SelfContained>
	<PublishSingleFile>false</PublishSingleFile>
	<PublishReadyToRun>false</PublishReadyToRun>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
</PropertyGroup>

<ItemGroup>
	<ProjectReference Include="..\UniversalDeviceToolkit.Lib\UniversalDeviceToolkit.Lib.csproj" />
</ItemGroup>

</Project>
