<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(UDTTargetFramework)</TargetFramework>
        <RootNamespace>UniversalDeviceToolkit.CLI.Lib</RootNamespace>
        <ImplicitUsings>disable</ImplicitUsings>
	    <Copyright>$(ProjectCopyright)</Copyright>
        <NeutralLanguage>en</NeutralLanguage>
    </PropertyGroup>
</Project>
