//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalDeviceToolkit.Lib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniversalDeviceToolkit.Lib.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string AccentColorSource_Custom {
            get {
                return ResourceManager.GetString("AccentColorSource_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string AccentColorSource_System {
            get {
                return ResourceManager.GetString("AccentColorSource_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string AlwaysOnUSBState_Off {
            get {
                return ResourceManager.GetString("AlwaysOnUSBState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On, always.
        /// </summary>
        public static string AlwaysOnUSBState_OnAlways {
            get {
                return ResourceManager.GetString("AlwaysOnUSBState_OnAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On, when sleeping.
        /// </summary>
        public static string AlwaysOnUSBState_OnWhenSleeping {
            get {
                return ResourceManager.GetString("AlwaysOnUSBState_OnWhenSleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile will not apply without AC adapter (Full wattage) connected..
        /// </summary>
        public static string AmdOverclocking_Ac_Message {
            get {
                return ResourceManager.GetString("AmdOverclocking_Ac_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not initialized..
        /// </summary>
        public static string AmdOverclocking_Not_Initialized_Message {
            get {
                return ResourceManager.GetString("AmdOverclocking_Not_Initialized_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported..
        /// </summary>
        public static string AmdOverclocking_Not_Supported {
            get {
                return ResourceManager.GetString("AmdOverclocking_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string AutorunState_Disabled {
            get {
                return ResourceManager.GetString("AutorunState_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string AutorunState_Enabled {
            get {
                return ResourceManager.GetString("AutorunState_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled, delayed.
        /// </summary>
        public static string AutorunState_EnabledDelayed {
            get {
                return ResourceManager.GetString("AutorunState_EnabledDelayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string BatteryNightChargeState_Off {
            get {
                return ResourceManager.GetString("BatteryNightChargeState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string BatteryNightChargeState_On {
            get {
                return ResourceManager.GetString("BatteryNightChargeState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conservation.
        /// </summary>
        public static string BatteryState_Conservation {
            get {
                return ResourceManager.GetString("BatteryState_Conservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string BatteryState_Normal {
            get {
                return ResourceManager.GetString("BatteryState_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid Charge.
        /// </summary>
        public static string BatteryState_RapidCharge {
            get {
                return ResourceManager.GetString("BatteryState_RapidCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Fan.
        /// </summary>
        public static string CustomFanCurveControl_Fan_CPU {
            get {
                return ResourceManager.GetString("CustomFanCurveControl_Fan_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU Fan.
        /// </summary>
        public static string CustomFanCurveControl_Fan_GPU {
            get {
                return ResourceManager.GetString("CustomFanCurveControl_Fan_GPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Fan.
        /// </summary>
        public static string CustomFanCurveControl_Fan_System {
            get {
                return ResourceManager.GetString("CustomFanCurveControl_Fan_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%.
        /// </summary>
        public static string DpiScale_DisplayName_Format {
            get {
                return ResourceManager.GetString("DpiScale_DisplayName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness must be between 0 and 9.
        /// </summary>
        public static string Exception_BrightnessRange {
            get {
                return ResourceManager.GetString("Exception_BrightnessRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built in display not found.
        /// </summary>
        public static string Exception_BuiltInDisplayNotFound {
            get {
                return ResourceManager.GetString("Exception_BuiltInDisplayNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read variable {0} from UEFI.
        /// </summary>
        public static string Exception_CannotReadVariableUEFI {
            get {
                return ResourceManager.GetString("Exception_CannotReadVariableUEFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set UEFI privileges.
        /// </summary>
        public static string Exception_CannotSetUEFIPrivileges {
            get {
                return ResourceManager.GetString("Exception_CannotSetUEFIPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write variable {0} to UEFI.
        /// </summary>
        public static string Exception_CannotWriteVariableUEFI {
            get {
                return ResourceManager.GetString("Exception_CannotWriteVariableUEFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t manage RGB keyboard with Vantage enabled.
        /// </summary>
        public static string Exception_CantManageWithVantage {
            get {
                return ResourceManager.GetString("Exception_CantManageWithVantage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command cannot be null or empty..
        /// </summary>
        public static string Exception_CommandCannotBeEmpty {
            get {
                return ResourceManager.GetString("Exception_CommandCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; failed with exit code {1}. {2}.
        /// </summary>
        public static string Exception_CommandExitedNonZero {
            get {
                return ResourceManager.GetString("Exception_CommandExitedNonZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command failed security validation: {0}.
        /// </summary>
        public static string Exception_CommandFailedSecurity {
            get {
                return ResourceManager.GetString("Exception_CommandFailedSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t deserialize effects.
        /// </summary>
        public static string Exception_CouldNotDeserializeEffects {
            get {
                return ResourceManager.GetString("Exception_CouldNotDeserializeEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get color &quot;{0}&quot;.
        /// </summary>
        public static string Exception_CouldNotGetColor {
            get {
                return ResourceManager.GetString("Exception_CouldNotGetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t read the {0} setting.
        /// </summary>
        public static string Exception_CouldNotReadRegistrySetting {
            get {
                return ResourceManager.GetString("Exception_CouldNotReadRegistrySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current process file name cannot be null.
        /// </summary>
        public static string Exception_CurrentProcessFileNameNull {
            get {
                return ResourceManager.GetString("Exception_CurrentProcessFileNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current process file version cannot be null.
        /// </summary>
        public static string Exception_CurrentProcessFileVersionNull {
            get {
                return ResourceManager.GetString("Exception_CurrentProcessFileVersionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user value is null.
        /// </summary>
        public static string Exception_CurrentUserValueNull {
            get {
                return ResourceManager.GetString("Exception_CurrentUserValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments contain dangerous characters.
        /// </summary>
        public static string Exception_DangerousArguments {
            get {
                return ResourceManager.GetString("Exception_DangerousArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous pattern detected in arguments for {0}.
        /// </summary>
        public static string Exception_DangerousPatternInArgs {
            get {
                return ResourceManager.GetString("Exception_DangerousPatternInArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of critical registry keys is not allowed.
        /// </summary>
        public static string Exception_DeletionCriticalRegistryNotAllowed {
            get {
                return ResourceManager.GetString("Exception_DeletionCriticalRegistryNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of system paths is not allowed.
        /// </summary>
        public static string Exception_DeletionSystemPathsNotAllowed {
            get {
                return ResourceManager.GetString("Exception_DeletionSystemPathsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device handle is not available.
        /// </summary>
        public static string Exception_DeviceHandleNotAvailable {
            get {
                return ResourceManager.GetString("Exception_DeviceHandleNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceIoControl returned 0, last error: {0}.
        /// </summary>
        public static string Exception_DeviceIoControlError {
            get {
                return ResourceManager.GetString("Exception_DeviceIoControlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceIoControl failed with error: {0}.
        /// </summary>
        public static string Exception_DeviceIoControlErrorWithCode {
            get {
                return ResourceManager.GetString("Exception_DeviceIoControlErrorWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device pack id mismatch. Expected &apos;{0}&apos;, got &apos;{1}&apos;..
        /// </summary>
        public static string Exception_DevicePackIdMismatch {
            get {
                return ResourceManager.GetString("Exception_DevicePackIdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device pack &apos;{0}&apos; manifest is empty..
        /// </summary>
        public static string Exception_DevicePackManifestEmpty {
            get {
                return ResourceManager.GetString("Exception_DevicePackManifestEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device pack &apos;{0}&apos; does not contain {1}..
        /// </summary>
        public static string Exception_DevicePackNoManifest {
            get {
                return ResourceManager.GetString("Exception_DevicePackNoManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device pack &apos;{0}&apos; is not available in the online resource catalog..
        /// </summary>
        public static string Exception_DevicePackNotAvailable {
            get {
                return ResourceManager.GetString("Exception_DevicePackNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device pack &apos;{0}&apos; is missing SHA256 metadata..
        /// </summary>
        public static string Exception_DevicePackSha256Missing {
            get {
                return ResourceManager.GetString("Exception_DevicePackSha256Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device pack contains an unsafe path: {0}.
        /// </summary>
        public static string Exception_DevicePackUnsafePath {
            get {
                return ResourceManager.GetString("Exception_DevicePackUnsafePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device pack contains unsupported file type: {0}.
        /// </summary>
        public static string Exception_DevicePackUnsupportedFileType {
            get {
                return ResourceManager.GetString("Exception_DevicePackUnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device pack &apos;{0}&apos; has an empty download URL..
        /// </summary>
        public static string Exception_DevicePackUrlEmpty {
            get {
                return ResourceManager.GetString("Exception_DevicePackUrlEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device pack vendor mismatch. Expected &apos;{0}&apos;, got &apos;{1}&apos;..
        /// </summary>
        public static string Exception_DevicePackVendorMismatch {
            get {
                return ResourceManager.GetString("Exception_DevicePackVendorMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device pack contains a Windows-style path separator: {0}.
        /// </summary>
        public static string Exception_DevicePackWindowsPathSep {
            get {
                return ResourceManager.GetString("Exception_DevicePackWindowsPathSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device property is not a GUID.
        /// </summary>
        public static string Exception_DevicePropertyNotGUID {
            get {
                return ResourceManager.GetString("Exception_DevicePropertyNotGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device property is not a string.
        /// </summary>
        public static string Exception_DevicePropertyNotString {
            get {
                return ResourceManager.GetString("Exception_DevicePropertyNotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending driver command: controlCode={0}.
        /// </summary>
        public static string Exception_DriverCommandError {
            get {
                return ResourceManager.GetString("Exception_DriverCommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting driver handle: {0}.
        /// </summary>
        public static string Exception_DriverHandleError {
            get {
                return ResourceManager.GetString("Exception_DriverHandleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get handle for driver: {0}.
        /// </summary>
        public static string Exception_DriverHandleFailed {
            get {
                return ResourceManager.GetString("Exception_DriverHandleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer did not exit in time..
        /// </summary>
        public static string Exception_ExplorerDidNotExit {
            get {
                return ResourceManager.GetString("Exception_ExplorerDidNotExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer did not restart in time..
        /// </summary>
        public static string Exception_ExplorerDidNotRestart {
            get {
                return ResourceManager.GetString("Exception_ExplorerDidNotRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize JSON.
        /// </summary>
        public static string Exception_FailedToDeserializeJSON {
            get {
                return ResourceManager.GetString("Exception_FailedToDeserializeJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize profile..
        /// </summary>
        public static string Exception_FailedToDeserializeProfile {
            get {
                return ResourceManager.GetString("Exception_FailedToDeserializeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register changes on task {0} in {1} [type={2}].
        /// </summary>
        public static string Exception_FailedToRegisterTask {
            get {
                return ResourceManager.GetString("Exception_FailedToRegisterTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start Explorer..
        /// </summary>
        public static string Exception_FailedToStartExplorer {
            get {
                return ResourceManager.GetString("Exception_FailedToStartExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify {0} state was set to {1}..
        /// </summary>
        public static string Exception_FailedVerifyState {
            get {
                return ResourceManager.GetString("Exception_FailedVerifyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan table length must be 10.
        /// </summary>
        public static string Exception_FanTableLength {
            get {
                return ResourceManager.GetString("Exception_FanTableLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File checksum mismatch.
        /// </summary>
        public static string Exception_FileChecksumMismatch {
            get {
                return ResourceManager.GetString("Exception_FileChecksumMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset with ID {0} not found.
        /// </summary>
        public static string Exception_GodModePresetNotFound {
            get {
                return ResourceManager.GetString("Exception_GodModePresetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to handle is invalid.
        /// </summary>
        public static string Exception_HandleInvalid {
            get {
                return ResourceManager.GetString("Exception_HandleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has to be readable.
        /// </summary>
        public static string Exception_HasToBeReadable {
            get {
                return ResourceManager.GetString("Exception_HasToBeReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has to be writable.
        /// </summary>
        public static string Exception_HasToBeWritable {
            get {
                return ResourceManager.GetString("Exception_HasToBeWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive shell executables require arguments when waiting for exit.
        /// </summary>
        public static string Exception_InteractiveShellRequiresArgs {
            get {
                return ResourceManager.GetString("Exception_InteractiveShellRequiresArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid action key.
        /// </summary>
        public static string Exception_InvalidActionKey {
            get {
                return ResourceManager.GetString("Exception_InvalidActionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid environment variable: {0}.
        /// </summary>
        public static string Exception_InvalidEnvVariable {
            get {
                return ResourceManager.GetString("Exception_InvalidEnvVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid environment variable value: {0}.
        /// </summary>
        public static string Exception_InvalidEnvVariableValue {
            get {
                return ResourceManager.GetString("Exception_InvalidEnvVariableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name.
        /// </summary>
        public static string Exception_InvalidFileName {
            get {
                return ResourceManager.GetString("Exception_InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid settings filename: {0}.
        /// </summary>
        public static string Exception_InvalidSettingsFilename {
            get {
                return ResourceManager.GetString("Exception_InvalidSettingsFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid state.
        /// </summary>
        public static string Exception_InvalidState {
            get {
                return ResourceManager.GetString("Exception_InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type of formatted.
        /// </summary>
        public static string Exception_InvalidTypeOfFormatted {
            get {
                return ResourceManager.GetString("Exception_InvalidTypeOfFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoCContainer already initialized.
        /// </summary>
        public static string Exception_IoCAlreadyInitialized {
            get {
                return ResourceManager.GetString("Exception_IoCAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoCContainer must be initialized first [type={0}].
        /// </summary>
        public static string Exception_IoCMustBeInitialized {
            get {
                return ResourceManager.GetString("Exception_IoCMustBeInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key {0} could not be opened.
        /// </summary>
        public static string Exception_KeyCouldNotBeOpened {
            get {
                return ResourceManager.GetString("Exception_KeyCouldNotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Module cannot be null.
        /// </summary>
        public static string Exception_MainModuleNull {
            get {
                return ResourceManager.GetString("Exception_MainModuleNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No God Mode preset is available..
        /// </summary>
        public static string Exception_NoGodModePresetAvailable {
            get {
                return ResourceManager.GetString("Exception_NoGodModePresetAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No God Mode preset could be created..
        /// </summary>
        public static string Exception_NoGodModePresetCreated {
            get {
                return ResourceManager.GetString("Exception_NoGodModePresetCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supported controller found.
        /// </summary>
        public static string Exception_NoSupportedControllerFound {
            get {
                return ResourceManager.GetString("Exception_NoSupportedControllerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supported feature found.
        /// </summary>
        public static string Exception_NoSupportedFeature {
            get {
                return ResourceManager.GetString("Exception_NoSupportedFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supported version found.
        /// </summary>
        public static string Exception_NoSupportedVersionFound {
            get {
                return ResourceManager.GetString("Exception_NoSupportedVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable not in allowlist: {0}.
        /// </summary>
        public static string Exception_NotInAllowlist {
            get {
                return ResourceManager.GetString("Exception_NotInAllowlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available.
        /// </summary>
        public static string Exception_NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("Exception_NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset and count exceed array bounds.
        /// </summary>
        public static string Exception_OffsetCountExceedArray {
            get {
                return ResourceManager.GetString("Exception_OffsetCountExceedArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Service Error.
        /// </summary>
        public static string Exception_OpenServiceError {
            get {
                return ResourceManager.GetString("Exception_OpenServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Service Manager Error.
        /// </summary>
        public static string Exception_OpenServiceManagerError {
            get {
                return ResourceManager.GetString("Exception_OpenServiceManagerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimization action not found: {0}.
        /// </summary>
        public static string Exception_OptimizationActionNotFound {
            get {
                return ResourceManager.GetString("Exception_OptimizationActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimization action cannot be reverted: {0}.
        /// </summary>
        public static string Exception_OptimizationActionRollbackUnavailable {
            get {
                return ResourceManager.GetString("Exception_OptimizationActionRollbackUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power mode switching is not supported on this device..
        /// </summary>
        public static string Exception_PowerModeNotSupported {
            get {
                return ResourceManager.GetString("Exception_PowerModeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power mode &apos;{0}&apos; is unavailable without AC adapter..
        /// </summary>
        public static string Exception_PowerModeUnavailableWithoutAC {
            get {
                return ResourceManager.GetString("Exception_PowerModeUnavailableWithoutAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell arguments contain dangerous patterns.
        /// </summary>
        public static string Exception_PowerShellDangerousArgs {
            get {
                return ResourceManager.GetString("Exception_PowerShellDangerousArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile file not found..
        /// </summary>
        public static string Exception_ProfileFileNotFound {
            get {
                return ResourceManager.GetString("Exception_ProfileFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile must be between 0 and 6.
        /// </summary>
        public static string Exception_ProfileRange {
            get {
                return ResourceManager.GetString("Exception_ProfileRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource catalog is empty..
        /// </summary>
        public static string Exception_ResourceCatalogEmpty {
            get {
                return ResourceManager.GetString("Exception_ResourceCatalogEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB Keyboard unsupported.
        /// </summary>
        public static string Exception_RGBKeyboardUnsupported {
            get {
                return ResourceManager.GetString("Exception_RGBKeyboardUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings path escapes allowed directory: {0}.
        /// </summary>
        public static string Exception_SettingsPathEscapesAllowedDir {
            get {
                return ResourceManager.GetString("Exception_SettingsPathEscapesAllowedDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup file URL could not be found.
        /// </summary>
        public static string Exception_SetupFileUrlNotFound {
            get {
                return ResourceManager.GetString("Exception_SetupFileUrlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded resource failed SHA256 validation. Expected {0}, got {1}..
        /// </summary>
        public static string Exception_SHA256ValidationFailed {
            get {
                return ResourceManager.GetString("Exception_SHA256ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table data cannot be empty.
        /// </summary>
        public static string Exception_TableDataCannotBeEmpty {
            get {
                return ResourceManager.GetString("Exception_TableDataCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name cannot be null or empty.
        /// </summary>
        public static string Exception_TagNameNullOrEmpty {
            get {
                return ResourceManager.GetString("Exception_TagNameNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature array must have exactly 10 elements.
        /// </summary>
        public static string Exception_TempArrayMustBe10 {
            get {
                return ResourceManager.GetString("Exception_TempArrayMustBe10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined value received: {0}.
        /// </summary>
        public static string Exception_UndefinedValueReceived {
            get {
                return ResourceManager.GetString("Exception_UndefinedValueReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown battery state: {0}.
        /// </summary>
        public static string Exception_UnknownBatteryState {
            get {
                return ResourceManager.GetString("Exception_UnknownBatteryState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown hive..
        /// </summary>
        public static string Exception_UnknownHive {
            get {
                return ResourceManager.GetString("Exception_UnknownHive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse version from tag name: &apos;{0}&apos;. Expected format: &apos;3.0.1&apos;.
        /// </summary>
        public static string Exception_UnparseableVersionFormat {
            get {
                return ResourceManager.GetString("Exception_UnparseableVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported power mode {0}.
        /// </summary>
        public static string Exception_UnsupportedPowerMode {
            get {
                return ResourceManager.GetString("Exception_UnsupportedPowerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update package integrity check failed: no SHA256 hash available for update {0}. Integrity check is required for security..
        /// </summary>
        public static string Exception_UpdateNoSHA256Hash {
            get {
                return ResourceManager.GetString("Exception_UpdateNoSHA256Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update package integrity check failed. Expected SHA256: {0}, Computed: {1}.
        /// </summary>
        public static string Exception_UpdateSHA256Mismatch {
            get {
                return ResourceManager.GetString("Exception_UpdateSHA256Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcard deletion is restricted.
        /// </summary>
        public static string Exception_WildcardDeletionRestricted {
            get {
                return ResourceManager.GetString("Exception_WildcardDeletionRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call failed: {0} [scope={1}, query={2}, methodName={3}].
        /// </summary>
        public static string Exception_WmiCallFailed {
            get {
                return ResourceManager.GetString("Exception_WmiCallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call failed: {0}. [scope={1}, query={2}, methodName={3}].
        /// </summary>
        public static string Exception_WmiCallFailedDot {
            get {
                return ResourceManager.GetString("Exception_WmiCallFailedDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMI class or namespace not available [scope={0}, query={1}].
        /// </summary>
        public static string Exception_WmiClassNotAvailable {
            get {
                return ResourceManager.GetString("Exception_WmiClassNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMI feature value is unavailable for {0}..
        /// </summary>
        public static string Exception_WmiFeatureUnavailable {
            get {
                return ResourceManager.GetString("Exception_WmiFeatureUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results in query.
        /// </summary>
        public static string Exception_WmiNoResults {
            get {
                return ResourceManager.GetString("Exception_WmiNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read failed: {0} [scope={1}, query={2}].
        /// </summary>
        public static string Exception_WmiReadFailed {
            get {
                return ResourceManager.GetString("Exception_WmiReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string FanMaxSpeedState_Off {
            get {
                return ResourceManager.GetString("FanMaxSpeedState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string FanMaxSpeedState_On {
            get {
                return ResourceManager.GetString("FanMaxSpeedState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        public static string FanMaxSpeedState_Toggle {
            get {
                return ResourceManager.GetString("FanMaxSpeedState_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string FlipToStartState_Off {
            get {
                return ResourceManager.GetString("FlipToStartState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string FlipToStartState_On {
            get {
                return ResourceManager.GetString("FlipToStartState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string FnLockState_Off {
            get {
                return ResourceManager.GetString("FnLockState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string FnLockState_On {
            get {
                return ResourceManager.GetString("FnLockState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered Off.
        /// </summary>
        public static string GPUController_PoweredOff {
            get {
                return ResourceManager.GetString("GPUController_PoweredOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered On.
        /// </summary>
        public static string GPUController_PoweredOn {
            get {
                return ResourceManager.GetString("GPUController_PoweredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string HardwareSensorsState_Off {
            get {
                return ResourceManager.GetString("HardwareSensorsState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string HardwareSensorsState_On {
            get {
                return ResourceManager.GetString("HardwareSensorsState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string HDRState_Off {
            get {
                return ResourceManager.GetString("HDRState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string HDRState_On {
            get {
                return ResourceManager.GetString("HDRState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dGPU.
        /// </summary>
        public static string HybridModeState_Off {
            get {
                return ResourceManager.GetString("HybridModeState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        public static string HybridModeState_On {
            get {
                return ResourceManager.GetString("HybridModeState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid-Auto.
        /// </summary>
        public static string HybridModeState_OnAuto {
            get {
                return ResourceManager.GetString("HybridModeState_OnAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid-iGPU.
        /// </summary>
        public static string HybridModeState_OnIGPUOnly {
            get {
                return ResourceManager.GetString("HybridModeState_OnIGPUOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC Adapter.
        /// </summary>
        public static string InstantBootState_AcAdapter {
            get {
                return ResourceManager.GetString("InstantBootState_AcAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC and USB PD.
        /// </summary>
        public static string InstantBootState_AcAdapterAndUsbPowerDelivery {
            get {
                return ResourceManager.GetString("InstantBootState_AcAdapterAndUsbPowerDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string InstantBootState_Off {
            get {
                return ResourceManager.GetString("InstantBootState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Power Delivery.
        /// </summary>
        public static string InstantBootState_UsbPowerDelivery {
            get {
                return ResourceManager.GetString("InstantBootState_UsbPowerDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Saving.
        /// </summary>
        public static string ITSMode_Intelligent_Battery_Saving {
            get {
                return ResourceManager.GetString("ITSMode_Intelligent_Battery_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligent Cooling.
        /// </summary>
        public static string ITSMode_Intelligent_Cooling {
            get {
                return ResourceManager.GetString("ITSMode_Intelligent_Cooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme Performance.
        /// </summary>
        public static string ITSMode_Intelligent_Extreme_Performance {
            get {
                return ResourceManager.GetString("ITSMode_Intelligent_Extreme_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geek.
        /// </summary>
        public static string ITSMode_Intelligent_Geek {
            get {
                return ResourceManager.GetString("ITSMode_Intelligent_Geek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurora Sync.
        /// </summary>
        public static string LampEffect_AuroraSync {
            get {
                return ResourceManager.GetString("LampEffect_AuroraSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breathe.
        /// </summary>
        public static string LampEffect_Breathe {
            get {
                return ResourceManager.GetString("LampEffect_Breathe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Pattern.
        /// </summary>
        public static string LampEffect_CustomPattern {
            get {
                return ResourceManager.GetString("LampEffect_CustomPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient.
        /// </summary>
        public static string LampEffect_Gradient {
            get {
                return ResourceManager.GetString("LampEffect_Gradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meteor.
        /// </summary>
        public static string LampEffect_Meteor {
            get {
                return ResourceManager.GetString("LampEffect_Meteor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow.
        /// </summary>
        public static string LampEffect_Rainbow {
            get {
                return ResourceManager.GetString("LampEffect_Rainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow Wave.
        /// </summary>
        public static string LampEffect_RainbowWave {
            get {
                return ResourceManager.GetString("LampEffect_RainbowWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ripple.
        /// </summary>
        public static string LampEffect_Ripple {
            get {
                return ResourceManager.GetString("LampEffect_Ripple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparkle.
        /// </summary>
        public static string LampEffect_Sparkle {
            get {
                return ResourceManager.GetString("LampEffect_Sparkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiral Rainbow.
        /// </summary>
        public static string LampEffect_SpiralRainbow {
            get {
                return ResourceManager.GetString("LampEffect_SpiralRainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        public static string LampEffect_Static {
            get {
                return ResourceManager.GetString("LampEffect_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave.
        /// </summary>
        public static string LampEffect_Wave {
            get {
                return ResourceManager.GetString("LampEffect_Wave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string MicrophoneState_Off {
            get {
                return ResourceManager.GetString("MicrophoneState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string MicrophoneState_On {
            get {
                return ResourceManager.GetString("MicrophoneState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        public static string ModifierKey_Alt {
            get {
                return ResourceManager.GetString("ModifierKey_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl.
        /// </summary>
        public static string ModifierKey_Ctrl {
            get {
                return ResourceManager.GetString("ModifierKey_Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string ModifierKey_Shift {
            get {
                return ResourceManager.GetString("ModifierKey_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics only (no system network changes).
        /// </summary>
        public static string NetworkAcceleration_Status_DiagnosticsOnly {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Status_DiagnosticsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off (default).
        /// </summary>
        public static string NetworkAcceleration_Status_Off {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Status_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running ({0}) loopback:{1}.
        /// </summary>
        public static string NetworkAcceleration_Status_Running {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Status_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped ({0}).
        /// </summary>
        public static string NetworkAcceleration_Status_Stopped {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Status_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker binary not found — build/install UniversalDeviceToolkit.NetworkProxy.exe.
        /// </summary>
        public static string NetworkAcceleration_Status_WorkerMissing {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Status_WorkerMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        public static string NotificationDuration_Long {
            get {
                return ResourceManager.GetString("NotificationDuration_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string NotificationDuration_Normal {
            get {
                return ResourceManager.GetString("NotificationDuration_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short.
        /// </summary>
        public static string NotificationDuration_Short {
            get {
                return ResourceManager.GetString("NotificationDuration_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom center.
        /// </summary>
        public static string NotificationPosition_BottomCenter {
            get {
                return ResourceManager.GetString("NotificationPosition_BottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom left.
        /// </summary>
        public static string NotificationPosition_BottomLeft {
            get {
                return ResourceManager.GetString("NotificationPosition_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom right.
        /// </summary>
        public static string NotificationPosition_BottomRight {
            get {
                return ResourceManager.GetString("NotificationPosition_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string NotificationPosition_Center {
            get {
                return ResourceManager.GetString("NotificationPosition_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center left.
        /// </summary>
        public static string NotificationPosition_CenterLeft {
            get {
                return ResourceManager.GetString("NotificationPosition_CenterLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center right.
        /// </summary>
        public static string NotificationPosition_CenterRight {
            get {
                return ResourceManager.GetString("NotificationPosition_CenterRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top center.
        /// </summary>
        public static string NotificationPosition_TopCenter {
            get {
                return ResourceManager.GetString("NotificationPosition_TopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top left.
        /// </summary>
        public static string NotificationPosition_TopLeft {
            get {
                return ResourceManager.GetString("NotificationPosition_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top right.
        /// </summary>
        public static string NotificationPosition_TopRight {
            get {
                return ResourceManager.GetString("NotificationPosition_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string OneLevelWhiteKeyboardBacklightState_Off {
            get {
                return ResourceManager.GetString("OneLevelWhiteKeyboardBacklightState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string OneLevelWhiteKeyboardBacklightState_On {
            get {
                return ResourceManager.GetString("OneLevelWhiteKeyboardBacklightState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk 1 Temperature.
        /// </summary>
        public static string OsdItem_Disk1Temperature {
            get {
                return ResourceManager.GetString("OsdItem_Disk1Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk 2 Temperature.
        /// </summary>
        public static string OsdItem_Disk2Temperature {
            get {
                return ResourceManager.GetString("OsdItem_Disk2Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Core Clock.
        /// </summary>
        public static string OsdItem_E_Core_Frequency {
            get {
                return ResourceManager.GetString("OsdItem_E_Core_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan.
        /// </summary>
        public static string OsdItem_Fan {
            get {
                return ResourceManager.GetString("OsdItem_Fan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPS.
        /// </summary>
        public static string OsdItem_Fps {
            get {
                return ResourceManager.GetString("OsdItem_Fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Time.
        /// </summary>
        public static string OsdItem_FrameTime {
            get {
                return ResourceManager.GetString("OsdItem_FrameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string OsdItem_Frequency {
            get {
                return ResourceManager.GetString("OsdItem_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1% Low.
        /// </summary>
        public static string OsdItem_LowFps {
            get {
                return ResourceManager.GetString("OsdItem_LowFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Temperature.
        /// </summary>
        public static string OsdItem_MemoryTemperature {
            get {
                return ResourceManager.GetString("OsdItem_MemoryTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motherboard Temperature.
        /// </summary>
        public static string OsdItem_MotherboardTemperature {
            get {
                return ResourceManager.GetString("OsdItem_MotherboardTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P-Core Clock.
        /// </summary>
        public static string OsdItem_P_Core_Frequency {
            get {
                return ResourceManager.GetString("OsdItem_P_Core_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string OsdItem_Power {
            get {
                return ResourceManager.GetString("OsdItem_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string OsdItem_Temperature {
            get {
                return ResourceManager.GetString("OsdItem_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilization.
        /// </summary>
        public static string OsdItem_Utilization {
            get {
                return ResourceManager.GetString("OsdItem_Utilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRAM Temperature.
        /// </summary>
        public static string OsdItem_VramTemperature {
            get {
                return ResourceManager.GetString("OsdItem_VramTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRAM Utilization.
        /// </summary>
        public static string OsdItem_VramUtilization {
            get {
                return ResourceManager.GetString("OsdItem_VramUtilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string OsdState_Hidden {
            get {
                return ResourceManager.GetString("OsdState_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string OsdState_Show {
            get {
                return ResourceManager.GetString("OsdState_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle State.
        /// </summary>
        public static string OsdState_Toggle {
            get {
                return ResourceManager.GetString("OsdState_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string OverdriveState_Off {
            get {
                return ResourceManager.GetString("OverdriveState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string OverdriveState_On {
            get {
                return ResourceManager.GetString("OverdriveState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string PanelLogoBacklightState_Off {
            get {
                return ResourceManager.GetString("PanelLogoBacklightState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string PanelLogoBacklightState_On {
            get {
                return ResourceManager.GetString("PanelLogoBacklightState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string PortsBacklightState_Off {
            get {
                return ResourceManager.GetString("PortsBacklightState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string PortsBacklightState_On {
            get {
                return ResourceManager.GetString("PortsBacklightState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string PowerModeMappingMode_Disabled {
            get {
                return ResourceManager.GetString("PowerModeMappingMode_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Power Mode.
        /// </summary>
        public static string PowerModeMappingMode_WindowsPowerMode {
            get {
                return ResourceManager.GetString("PowerModeMappingMode_WindowsPowerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Power Plan.
        /// </summary>
        public static string PowerModeMappingMode_WindowsPowerPlan {
            get {
                return ResourceManager.GetString("PowerModeMappingMode_WindowsPowerPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string PowerModeState_Balance {
            get {
                return ResourceManager.GetString("PowerModeState_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme.
        /// </summary>
        public static string PowerModeState_Extreme {
            get {
                return ResourceManager.GetString("PowerModeState_Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string PowerModeState_GodMode {
            get {
                return ResourceManager.GetString("PowerModeState_GodMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string PowerModeState_Performance {
            get {
                return ResourceManager.GetString("PowerModeState_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiet.
        /// </summary>
        public static string PowerModeState_Quiet {
            get {
                return ResourceManager.GetString("PowerModeState_Quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hz.
        /// </summary>
        public static string RefreshRate_DisplayName_Format {
            get {
                return ResourceManager.GetString("RefreshRate_DisplayName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} × {1}.
        /// </summary>
        public static string Resolution_DisplayName_Format {
            get {
                return ResourceManager.GetString("Resolution_DisplayName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string RGBKeyboardBacklightBrightness_High {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightBrightness_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string RGBKeyboardBacklightBrightness_Low {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightBrightness_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breath.
        /// </summary>
        public static string RGBKeyboardBacklightEffect_Breath {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_Breath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth.
        /// </summary>
        public static string RGBKeyboardBacklightEffect_Smooth {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        public static string RGBKeyboardBacklightEffect_Static {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Left.
        /// </summary>
        public static string RGBKeyboardBacklightEffect_WaveLTR {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_WaveLTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Right.
        /// </summary>
        public static string RGBKeyboardBacklightEffect_WaveRTL {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_WaveRTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset 4.
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Four {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Off {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset 1.
        /// </summary>
        public static string RGBKeyboardBacklightPreset_One {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset 3.
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Three {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset 2.
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Two {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string RGBKeyboardBacklightSpeed_Fast {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightSpeed_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastest.
        /// </summary>
        public static string RGBKeyboardBacklightSpeed_Fastest {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightSpeed_Fastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string RGBKeyboardBacklightSpeed_Slow {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightSpeed_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slowest.
        /// </summary>
        public static string RGBKeyboardBacklightSpeed_Slowest {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightSpeed_Slowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string SpeakerState_Mute {
            get {
                return ResourceManager.GetString("SpeakerState_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute.
        /// </summary>
        public static string SpeakerState_Unmute {
            get {
                return ResourceManager.GetString("SpeakerState_Unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string SpectrumKeyboardBacklightBrightness_High {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightBrightness_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string SpectrumKeyboardBacklightBrightness_Low {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightBrightness_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string SpectrumKeyboardBacklightBrightness_Medium {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightBrightness_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string SpectrumKeyboardBacklightBrightness_Off {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightBrightness_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom to Top.
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_BottomToTop {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_BottomToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clockwise.
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_Clockwise {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_Clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Clockwise.
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_CounterClockwise {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_CounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left to Right.
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_LeftToRight {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_LeftToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to Left.
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_RightToLeft {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_RightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top to Bottom.
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_TopToBottom {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_TopToBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Always {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Bounce.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_AudioBounce {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_AudioBounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Ripple.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_AudioRipple {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_AudioRipple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurora Sync.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_AuroraSync {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_AuroraSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Change.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_ColorChange {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_ColorChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Pulse.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_ColorPulse {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_ColorPulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Wave.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_ColorWave {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_ColorWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Rain {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow Screw.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_RainbowScrew {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_RainbowScrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow Wave.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_RainbowWave {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_RainbowWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ripple.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Ripple {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Ripple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Smooth {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Type {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string SpectrumKeyboardBacklightSpeed_Speed1 {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightSpeed_Speed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string SpectrumKeyboardBacklightSpeed_Speed2 {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightSpeed_Speed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string SpectrumKeyboardBacklightSpeed_Speed3 {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightSpeed_Speed3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Theme_System {
            get {
                return ResourceManager.GetString("Theme_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Style.
        /// </summary>
        public static string ThemeStylePreset_Default {
            get {
                return ResourceManager.GetString("ThemeStylePreset_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest Tech.
        /// </summary>
        public static string ThemeStylePreset_Forest {
            get {
                return ResourceManager.GetString("ThemeStylePreset_Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midnight Neon.
        /// </summary>
        public static string ThemeStylePreset_Midnight {
            get {
                return ResourceManager.GetString("ThemeStylePreset_Midnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official Cool.
        /// </summary>
        public static string ThemeStylePreset_Official {
            get {
                return ResourceManager.GetString("ThemeStylePreset_Official", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string TouchpadLockState_Off {
            get {
                return ResourceManager.GetString("TouchpadLockState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string TouchpadLockState_On {
            get {
                return ResourceManager.GetString("TouchpadLockState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string UpdateCheckFrequency_PerDay {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every hour.
        /// </summary>
        public static string UpdateCheckFrequency_PerHour {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string UpdateCheckFrequency_PerMonth {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 3 hours.
        /// </summary>
        public static string UpdateCheckFrequency_PerThreeHours {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerThreeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 12 hours.
        /// </summary>
        public static string UpdateCheckFrequency_PerTwelveHours {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerTwelveHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string UpdateCheckFrequency_PerWeek {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string WhiteKeyboardBacklightState_High {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string WhiteKeyboardBacklightState_Low {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string WhiteKeyboardBacklightState_Off {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to macOS.
        /// </summary>
        public static string WindowBackdropStyle_macOS {
            get {
                return ResourceManager.GetString("WindowBackdropStyle_macOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string WindowBackdropStyle_Windows {
            get {
                return ResourceManager.GetString("WindowBackdropStyle_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the current optimization to finish..
        /// </summary>
        public static string WindowsOptimizationPage_Optimization_Busy_Wait {
            get {
                return ResourceManager.GetString("WindowsOptimizationPage_Optimization_Busy_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change could not be verified. Administrator privileges may be required..
        /// </summary>
        public static string WindowsOptimizationPage_Optimization_NotVerified {
            get {
                return ResourceManager.GetString("WindowsOptimizationPage_Optimization_NotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string WinKeyState_Off {
            get {
                return ResourceManager.GetString("WinKeyState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string WinKeyState_On {
            get {
                return ResourceManager.GetString("WinKeyState_On", resourceCulture);
            }
        }

        public static string SettingsBackup_MissingManifest {
            get {
                return ResourceManager.GetString("SettingsBackup_MissingManifest", resourceCulture);
            }
        }

        public static string SettingsBackup_InvalidManifest {
            get {
                return ResourceManager.GetString("SettingsBackup_InvalidManifest", resourceCulture);
            }
        }

        public static string SettingsBackup_NewerFormat {
            get {
                return ResourceManager.GetString("SettingsBackup_NewerFormat", resourceCulture);
            }
        }

        public static string SettingsBackup_UnsafeEntry {
            get {
                return ResourceManager.GetString("SettingsBackup_UnsafeEntry", resourceCulture);
            }
        }
    }
}
