//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalDeviceToolkit.Lib.Macro.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniversalDeviceToolkit.Lib.Macro.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string MacroSource_Keyboard {
            get {
                return ResourceManager.GetString("MacroSource_Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        public static string MacroSource_Mouse {
            get {
                return ResourceManager.GetString("MacroSource_Mouse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MOVE.
        /// </summary>
        public static string MacroEventControl_MouseMove_Title {
            get {
                return ResourceManager.GetString("MacroEventControl_MouseMove_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WHEEL DOWN.
        /// </summary>
        public static string MacroEventControl_MouseWheelDown_Title {
            get {
                return ResourceManager.GetString("MacroEventControl_MouseWheelDown_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WHEEL UP.
        /// </summary>
        public static string MacroEventControl_MouseWheelUp_Title {
            get {
                return ResourceManager.GetString("MacroEventControl_MouseWheelUp_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WHEEL LEFT.
        /// </summary>
        public static string MacroEventControl_MouseWheelLeft_Title {
            get {
                return ResourceManager.GetString("MacroEventControl_MouseWheelLeft_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WHEEL RIGHT.
        /// </summary>
        public static string MacroEventControl_MouseWheelRight_Title {
            get {
                return ResourceManager.GetString("MacroEventControl_MouseWheelRight_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to XBUTTON{0}.
        /// </summary>
        public static string MacroEventControl_MouseXButton_Title {
            get {
                return ResourceManager.GetString("MacroEventControl_MouseXButton_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LBUTTON.
        /// </summary>
        public static string MacroEventControl_MouseLButton_Title {
            get {
                return ResourceManager.GetString("MacroEventControl_MouseLButton_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RBUTTON.
        /// </summary>
        public static string MacroEventControl_MouseRButton_Title {
            get {
                return ResourceManager.GetString("MacroEventControl_MouseRButton_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MBUTTON.
        /// </summary>
        public static string MacroEventControl_MouseMButton_Title {
            get {
                return ResourceManager.GetString("MacroEventControl_MouseMButton_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BUTTON{0}.
        /// </summary>
        public static string MacroEventControl_MouseButton_Title {
            get {
                return ResourceManager.GetString("MacroEventControl_MouseButton_Title", resourceCulture);
            }
        }
    }
}
