using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace UniversalDeviceToolkit.Lib.Network;

/// <summary>
/// PAC file generation stub. Phase 1 emits a minimal FindProxyForURL that DIRECT-s everything
/// unless domain rules are supplied (then PROXY loopback). Not a production rules pack.
/// </summary>
public static class PacFileGenerator
{
    public static string Generate(int proxyPort, IEnumerable<string>? proxiedDomains = null)
    {
        if (proxyPort is <= 0 or > 65535)
            throw new ArgumentOutOfRangeException(nameof(proxyPort));

        var domains = (proxiedDomains ?? [])
            .Where(d => !string.IsNullOrWhiteSpace(d))
            .Select(d => d.Trim().ToLowerInvariant())
            .Distinct(StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Universal Device Toolkit");
        sb.AppendLine("// Loopback-only proxy; DIRECT by default for non-matching hosts.");
        sb.AppendLine("function FindProxyForURL(url, host) {");
        sb.AppendLine("  host = host.toLowerCase();");

        if (domains.Count > 0)
        {
            sb.Append("  var domains = [");
            sb.Append(string.Join(", ", domains.Select(d => $"\"{EscapeJs(d)}\"")));
            sb.AppendLine("];");
            sb.AppendLine("  for (var i = 0; i < domains.length; i++) {");
            sb.AppendLine("    if (host === domains[i] || dnsDomainIs(host, \".\" + domains[i])) {");
            sb.AppendLine(
                $"      return \"PROXY 127.0.0.1:{proxyPort}; PROXY [::1]:{proxyPort}; DIRECT\";");
            sb.AppendLine("    }");
            sb.AppendLine("  }");
        }

        sb.AppendLine("  return \"DIRECT\";");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EscapeJs(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
}
