<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(UDTTargetFramework)</TargetFramework>
    <RootNamespace>HardwareValidation</RootNamespace>
    <EnableUdtTestHooks>true</EnableUdtTestHooks>

  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\Device\UniversalDeviceToolkit.Lib.csproj" />
  </ItemGroup>

</Project>
